// /*
//     Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import gsap from 'gsap'
// import { useGSAP } from '@gsap/react'
// import { useRef, useState } from 'react'
// import { Float, useGLTF, useTexture } from '@react-three/drei'

// const Cube = ({ ...props }) => {
//   const { nodes } = useGLTF('models/cube.glb')

//   const texture = useTexture('textures/cube.png')

//   const cubeRef = useRef()
//   const [hovered, setHovered] = useState(false)

//   useGSAP(() => {
//     gsap
//       .timeline({
//         repeat: -1,
//         repeatDelay: 0.5,
//       })
//       .to(cubeRef.current.rotation, {
//         y: hovered ? '+=2' : `+=${Math.PI * 2}`,
//         x: hovered ? '+=2' : `-=${Math.PI * 2}`,
//         duration: 2.5,
//         stagger: {
//           each: 0.15,
//         },
//       })
//   })

//   return (
//     <Float floatIntensity={2}>
//       <group
//         position={[9, -4, 0]}
//         rotation={[2.6, 0.8, -1.8]}
//         scale={0.5}
//         dispose={null}
//         {...props}
//       >
//         <mesh
//           ref={cubeRef}
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube.geometry}
//           material={nodes.Cube.material}
//           onPointerEnter={() => setHovered(true)}
//         >
//           <meshMatcapMaterial matcap={texture} toneMapped={false} />
//         </mesh>
//       </group>
//     </Float>
//   )
// }

// useGLTF.preload('models/cube.glb')

// export default Cube

import { useGLTF, Float } from '@react-three/drei'
import { useState, useRef } from 'react'

const Laptop = (props) => {
  const laptopRef = useRef()
  const { nodes, materials } = useGLTF('/models/laptop.glb')

  return (
    <Float floatIntensity={1}>
      <group {...props} scale={0.3}>
        <mesh
          geometry={nodes.Object_4.geometry}
          ref={laptopRef}
          material={materials.palette}
          // rotation={[Math.PI / 2, Math.PI / 2, 2]}
          onPointerEnter={() => setHovered(true)}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['palette.001']}
          ref={laptopRef}
          // rotation={[Math.PI / 2, Math.PI / 2, 2]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/laptop.glb')
export default Laptop
